"""Markdown report -- for PR comments, CI job summaries and issue templates."""

from __future__ import annotations

from typing import List

from ..detectors.base import Severity
from ..diagnosis import Diagnosis

_BADGE = {
    Severity.CRITICAL: "🔴 **CRITICAL**",
    Severity.WARNING: "🟠 **WARNING**",
    Severity.INFO: "🔵 INFO",
    Severity.OK: "🟢 OK",
    Severity.SKIPPED: "⚪ skipped",
}


def render(diagnosis: Diagnosis) -> str:
    run = diagnosis.run
    out: List[str] = [f"## rldoctor report — `{run.name}`", ""]

    facts = [f"**{run.n_steps}** steps", f"**{len(run.available_fields)}** metrics"]
    if run.config.algorithm:
        facts.append(f"algorithm **{run.config.algorithm.upper()}**")
    if run.config.model_name:
        facts.append(f"model `{run.config.model_name}`")
    out += [" · ".join(facts), ""]

    headline = diagnosis.cost.headline()
    if headline:
        out += [f"> ⚠️ {headline}", ""]

    problems = diagnosis.problems
    if not problems:
        out += ["✅ Every applicable check passed.", ""]
    else:
        out += ["| | Check | Verdict |", "|---|---|---|"]
        for finding in problems:
            summary = finding.summary.replace("\n", " ").replace("|", "\\|")
            out.append(f"| {_BADGE[finding.severity]} | {finding.title} | {summary} |")
        out.append("")

        for finding in problems:
            out += [f"### {_BADGE[finding.severity]} — {finding.title}", "", finding.summary, ""]
            if finding.evidence:
                out += ["<details><summary>Evidence</summary>", ""]
                out += [f"- {item}" for item in finding.evidence]
                out += ["", "</details>", ""]
            if finding.prescription:
                out += ["**What to change**", ""]
                out += [f"{i}. {item}" for i, item in enumerate(finding.prescription, 1)]
                out.append("")
            if finding.references:
                out += ["<details><summary>References</summary>", ""]
                out += [f"- {item}" for item in finding.references]
                out += ["", "</details>", ""]

    passed = diagnosis.passed
    skipped = diagnosis.skipped
    if passed:
        out += [f"**Passed:** {', '.join(f'`{f.detector}`' for f in passed)}", ""]
    if skipped:
        out += ["<details><summary>Skipped checks (insufficient data)</summary>", ""]
        out += [f"- `{f.detector}` — {f.summary}" for f in skipped]
        out += ["", "</details>", ""]

    out += ["", f"<sub>Generated by [rldoctor](https://github.com/junglezke/rldoctor) v{diagnosis.version}</sub>"]
    return "\n".join(out)
